ansible_python_interpreter: /usr/local/bin/python2

pf_open_ports:
  - ssh
  - http
  - https

nginx_alt_server_names:
  - lenon.com.br
  - lenon.ninja
  - www.lenon.com.br
  - www.lenon.ninja
  - www.lenonmarcel.com.br

nginx_server_name: lenonmarcel.com.br

nginx_cert_crt: /usr/local/etc/nginx/ssl/lenonmarcel_com_br.crt
nginx_cert_key: /usr/local/etc/nginx/ssl/lenonmarcel_com_br.key
nginx_dhparam: /usr/local/etc/nginx/ssl/dhparams.pem

aliases:
  - { user: root, alias: contato@lenon.com.br }
