- name: install nginx package
  pkgng: name=nginx
  sudo: yes

- name: start nginx
  service: name=nginx state=started enabled=yes
  sudo: yes

- name: update nginx.conf
  template: src=nginx.conf.j2 dest=/usr/local/etc/nginx/nginx.conf
            owner=root group=wheel mode=0644
  notify: restart nginx
  sudo: yes

- name: create certs dir
  file: path=/usr/local/etc/nginx/ssl state=directory mode=0700
  sudo: yes
