- name: load kernel module
  command: /sbin/kldload pf creates=/dev/pf
  sudo: yes

- name: copy pf config
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=root group=wheel mode=0644
  sudo: yes
  notify: reload pf

- name: enable pf
  service: name=pf state=started enabled=yes
  sudo: yes

- name: check if pf is enabled
  command: /sbin/pfctl -s info
  sudo: yes
  register: pfctl_info

- name: start pf
  command: pfctl -e
  when: pfctl_info.stdout.find('Enabled') == -1
  sudo: yes
