- name: copy pf config
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=root group=wheel mode=0644
  sudo: yes
  notify: reload pf

- name: enable pf
  service: name=pf state=started enabled=yes
  sudo: yes

- shell: pfctl -s info
  register: pfctl_info
  sudo: yes

- name: start pf
  command: pfctl -e
  when: pfctl_info.stdout.find('Enabled') == -1
  sudo: yes
