- hosts:
    - www
  become: yes
  tasks:
    - name: fetch updates
      command: /usr/sbin/freebsd-update fetch
    - name: install updates
      command: /usr/sbin/freebsd-update install
    - name: reboot server
      command: reboot
      ignore_errors: true
